name: Commit on Accepted Roots update

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    # Run Hourly
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check_release:
    runs-on: ubuntu-latest
    name: Hourly check for updates to logs' Accepted Roots

    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v6

    - name: Setup git
      run: |
          git config --global user.email "gh@crt.sh"
          git config --global user.name "ctloglists"

    - name: Fetch all branches
      run: git fetch origin

    - name: Run check_for_acceptedroots_changes.sh
      run: chmod +x cmd/acceptedroots/check_for_acceptedroots_changes.sh; cmd/acceptedroots/check_for_acceptedroots_changes.sh

    - name: Check for changes to logs' Accepted Roots
      run: |
        git fetch origin main
        if [[ $(git diff --staged -U0 "files/acceptedroots/*") ]]; then
          echo "Commit needed: At least one log's Accepted Roots have been updated."
          echo "commit_needed=true" >> $GITHUB_ENV
          echo "commit_message=At least one log's Accepted Roots have been updated" >> $GITHUB_ENV
        else
          echo "No logs' Accepted Roots have been updated."
          echo "commit_needed=false" >> $GITHUB_ENV
        fi

    - name: Commit changes
      if: env.commit_needed == 'true'
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: ${{ env.commit_message }}
